const express = require('express');
const router = express.Router();
const { upload } = require('../config/cloudinary');
const { protect } = require('../middlewares/auth');
const AppError = require('../utils/AppError');

// @desc    Upload file to Cloudinary
// @route   POST /api/upload
// @access  Private (Admin)
router.post('/', protect, upload.single('image'), (req, res, next) => {
  if (!req.file) {
    return next(new AppError('Please upload an image file', 400));
  }

  res.status(200).json({
    success: true,
    message: 'Image uploaded successfully to Cloudinary',
    url: req.file.path, // Secure URL generated by Cloudinary
    publicId: req.file.filename // Public ID of the image in Cloudinary
  });
});

module.exports = router;
